apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-with-circleci
  title: app-with-circleci
  description: app with GitHub + CircleCI integration
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in service info
      required:
        - name
      properties:
        name:
          title: Service Name
          type: string
          description: Unique name of your service
          ui:autofocus: true

    - title: Choose GitHub repository location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: object
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            requestUserRepoCreation: true

    - title: CircleCI Setup
      properties:
        circleci:
          title: CircleCI Token
          type: string
          description: API token with access to follow the project
          ui:help: 'You can create a personal API token at https://circleci.com/account/api'

  steps:
    - id: fetch
      name: Fetch Node.js frontend template
      action: fetch:plain
      input:
        url: https://github.com/stone-monkeys/engineering-repo-templates/tree/main/frontend-templates/node
        targetPath: ./workspace

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: Node.js frontend created from template
        sourcePath: ./workspace
        defaultBranch: main
        allowedHosts: ['github.com']

    - id: setup-circleci
      name: Enable CircleCI on the new repo
      action: custom:command:execute
      input:
        command: >
          curl -sf -X POST https://circleci.com/api/v1.1/project/github/${{ parameters.repoUrl.owner }}/${{ parameters.repoUrl.repoName }}/follow 
          -H "Circle-Token: ${{ parameters.circleci }}"
