# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test

      # Docker build and push to Docker Hub
      - run:
          name: Build Docker Image
          command: |
            # Log in to Docker Hub
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

            # Build the Docker image
            docker build -t $DOCKER_USERNAME/backstage-circleci-integration:latest .

            # Push the Docker image to Docker Hub
            docker push $DOCKER_USERNAME/backstage-circleci-integration:latest

workflows:
  version: 2
  build:
    jobs:
      - build
