# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test

      # Docker build step
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image"
            docker build -t backstage-circleci-integration:latest .
      # Docker push step
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "Pushing Docker image to Docker Hub"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME/backstage-circleci-integration:latest"

workflows:
  version: 2
  build:
    jobs:
      - build
